# 武器统一配置：
# - 集中维护所有武器数值与脚本映射
# - 便于统一平衡与扩展新武器
# - 可选 affix_ids: [] 用于武器词条，运行时也可追加
extends RefCounted
class_name WeaponDefs

const WEAPON_DEFS := [
	{
		"id": "blade_short",
		"type": "melee",
		"type_affix_id": "type_blade",
		"theme_affix_id": "theme_classical",
		"script_path": "res://scripts/weapons/melee/weapon_blade_short.gd",
		"name_key": "weapon.blade_short.name",
		"desc_key": "weapon.blade_short.desc",
		"base_cost": 5,
		"color": Color(0.95, 0.30, 0.30, 1.0),
		"swing_texture_path": "res://assets/weapons/swing_blade_short.png",
		"icon_path": "res://assets/weapons/blade_short.png",
		"stats": {
			"damage": 14,
			"cooldown": 0.40,
			"range": 74.0,
			"touch_interval": 0.38,
			"swing_duration": 0.20,
			"swing_degrees": 110.0,
			"swing_reach": 22.0,
			"hitbox_radius": 14.0
		}
	},
	{
		"id": "dagger",
		"type": "melee",
		"type_affix_id": "type_blade",
		"theme_affix_id": "theme_classical",
		"script_path": "res://scripts/weapons/melee/weapon_dagger.gd",
		"name_key": "weapon.dagger.name",
		"desc_key": "weapon.dagger.desc",
		"base_cost": 4,
		"color": Color(0.60, 0.65, 0.75, 1.0),
		"swing_texture_path": "res://assets/weapons/swing_dagger.png",
		"icon_path": "res://assets/weapons/dagger.png",
		"stats": {
			"damage": 10,
			"cooldown": 0.28,
			"range": 68.0,
			"touch_interval": 0.25,
			"swing_duration": 0.12,
			"swing_degrees": 30.0,
			"swing_reach": 18.0,
			"hitbox_radius": 12.0
		}
	},
	{
		"id": "spear",
		"type": "melee",
		"type_affix_id": "type_spear",
		"theme_affix_id": "theme_classical",
		"script_path": "res://scripts/weapons/melee/weapon_spear.gd",
		"name_key": "weapon.spear.name",
		"desc_key": "weapon.spear.desc",
		"base_cost": 7,
		"color": Color(0.55, 0.60, 0.70, 1.0),
		"swing_texture_path": "res://assets/weapons/swing_spear.png",
		"icon_path": "res://assets/weapons/spear.png",
		"stats": {
			"damage": 18,
			"cooldown": 0.55,
			"range": 95.0,
			"touch_interval": 0.42,
			"swing_duration": 0.22,
			"swing_degrees": 40.0,
			"swing_reach": 34.0,
			"hitbox_radius": 14.0
		}
	},
	{
		"id": "chainsaw",
		"type": "melee",
		"type_affix_id": "type_blade",
		"theme_affix_id": "theme_modern",
		"script_path": "res://scripts/weapons/melee/weapon_chainsaw.gd",
		"name_key": "weapon.chainsaw.name",
		"desc_key": "weapon.chainsaw.desc",
		"base_cost": 12,
		"color": Color(0.35, 0.38, 0.40, 1.0),
		"swing_texture_path": "res://assets/weapons/swing_chainsaw.png",
		"icon_path": "res://assets/weapons/chainsaw.png",
		"stats": {
			"damage": 6,
			"cooldown": 0.85,
			"range": 72.0,
			"touch_interval": 0.15,
			"swing_duration": 0.20,
			"swing_degrees": 360.0,
			"swing_reach": 24.0,
			"hitbox_radius": 16.0,
			"spin_duration": 0.6
		}
	},
	{
		"id": "hammer_heavy",
		"type": "melee",
		"type_affix_id": "type_spear",
		"theme_affix_id": "theme_classical",
		"script_path": "res://scripts/weapons/melee/weapon_hammer_heavy.gd",
		"name_key": "weapon.hammer_heavy.name",
		"desc_key": "weapon.hammer_heavy.desc",
		"base_cost": 8,
		"color": Color(0.90, 0.58, 0.24, 1.0),
		"swing_texture_path": "res://assets/weapons/swing_hammer_heavy.png",
		"icon_path": "res://assets/weapons/hammer_heavy.png",
		"stats": {
			"damage": 24,
			"cooldown": 0.72,
			"range": 86.0,
			"touch_interval": 0.50,
			"swing_duration": 0.24,
			"swing_degrees": 96.0,
			"swing_reach": 26.0,
			"hitbox_radius": 16.0
		}
	},
	{
		"id": "pistol_basic",
		"type": "ranged",
		"type_affix_id": "type_firearm",
		"theme_affix_id": "theme_modern",
		"script_path": "res://scripts/weapons/ranged/weapon_pistol_basic.gd",
		"name_key": "weapon.pistol_basic.name",
		"desc_key": "weapon.pistol_basic.desc",
		"base_cost": 6,
		"color": Color(0.25, 0.80, 0.95, 1.0),
		"bullet_type": "pistol",
		"icon_path": "res://assets/weapons/pistol_basic.png",
		"bullet_texture_path": "res://assets/bullets/bullet_firearm.png",
		"bullet_collision_radius": 3.0,
		"stats": {"damage": 8, "cooldown": 0.28, "range": 1200.0, "bullet_speed": 520.0, "pellet_count": 1, "spread_degrees": 0.0, "bullet_pierce": 0}
	},
	{
		"id": "shotgun_wide",
		"type": "ranged",
		"type_affix_id": "type_firearm",
		"theme_affix_id": "theme_modern",
		"script_path": "res://scripts/weapons/ranged/weapon_shotgun_wide.gd",
		"name_key": "weapon.shotgun_wide.name",
		"desc_key": "weapon.shotgun_wide.desc",
		"base_cost": 9,
		"color": Color(0.50, 0.88, 0.30, 1.0),
		"bullet_type": "shotgun",
		"icon_path": "res://assets/weapons/shotgun_wide.png",
		"bullet_texture_path": "res://assets/bullets/bullet_firearm.png",
		"bullet_collision_radius": 4.0,
		"stats": {"damage": 6, "cooldown": 0.46, "range": 980.0, "bullet_speed": 460.0, "pellet_count": 3, "spread_degrees": 20.0, "bullet_pierce": 0}
	},
	{
		"id": "rifle_long",
		"type": "ranged",
		"type_affix_id": "type_firearm",
		"theme_affix_id": "theme_modern",
		"script_path": "res://scripts/weapons/ranged/weapon_rifle_long.gd",
		"name_key": "weapon.rifle_long.name",
		"desc_key": "weapon.rifle_long.desc",
		"base_cost": 10,
		"color": Color(0.65, 0.66, 0.95, 1.0),
		"bullet_type": "rifle",
		"icon_path": "res://assets/weapons/rifle_long.png",
		"bullet_texture_path": "res://assets/bullets/bullet_firearm.png",
		"bullet_collision_radius": 2.0,
		"stats": {"damage": 12, "cooldown": 0.52, "range": 1400.0, "bullet_speed": 700.0, "pellet_count": 1, "spread_degrees": 0.0, "bullet_pierce": 1}
	},
	{
		"id": "wand_focus",
		"type": "ranged",
		"type_affix_id": "type_staff",
		"theme_affix_id": "theme_fantasy",
		"script_path": "res://scripts/weapons/ranged/weapon_wand_focus.gd",
		"name_key": "weapon.wand_focus.name",
		"desc_key": "weapon.wand_focus.desc",
		"base_cost": 7,
		"color": Color(0.88, 0.46, 0.95, 1.0),
		"bullet_type": "laser",
		"icon_path": "res://assets/weapons/wand_focus.png",
		"bullet_texture_path": "res://assets/bullets/bullet_laser.png",
		"bullet_collision_radius": 2.0,
		"stats": {"damage": 9, "cooldown": 0.34, "range": 1180.0, "bullet_speed": 560.0, "pellet_count": 2, "spread_degrees": 10.0, "bullet_pierce": 0}
	},
	{
		"id": "sniper",
		"type": "ranged",
		"type_affix_id": "type_firearm",
		"theme_affix_id": "theme_scifi",
		"script_path": "res://scripts/weapons/ranged/weapon_sniper.gd",
		"name_key": "weapon.sniper.name",
		"desc_key": "weapon.sniper.desc",
		"base_cost": 14,
		"color": Color(0.45, 0.50, 0.55, 1.0),
		"bullet_type": "rifle",
		"icon_path": "res://assets/weapons/sniper.png",
		"bullet_texture_path": "res://assets/bullets/bullet_firearm.png",
		"bullet_collision_radius": 2.0,
		"stats": {"damage": 28, "cooldown": 0.95, "range": 2200.0, "bullet_speed": 900.0, "pellet_count": 1, "spread_degrees": 0.0, "bullet_pierce": 2}
	},
	{
		"id": "orb_wand",
		"type": "ranged",
		"type_affix_id": "type_staff",
		"theme_affix_id": "theme_xuanhuan",
		"script_path": "res://scripts/weapons/ranged/weapon_orb_wand.gd",
		"name_key": "weapon.orb_wand.name",
		"desc_key": "weapon.orb_wand.desc",
		"base_cost": 8,
		"color": Color(0.95, 0.70, 0.35, 1.0),
		"bullet_type": "orb",
		"icon_path": "res://assets/weapons/orb_wand.png",
		"bullet_texture_path": "res://assets/bullets/bullet_orb.png",
		"bullet_collision_radius": 4.0,
		"stats": {"damage": 11, "cooldown": 0.38, "range": 800.0, "bullet_speed": 420.0, "pellet_count": 1, "spread_degrees": 0.0, "bullet_pierce": 0}
	},
	{
		"id": "blade_long",
		"type": "melee",
		"type_affix_id": "type_blade",
		"theme_affix_id": "theme_classical",
		"script_path": "res://scripts/weapons/melee/weapon_blade_long.gd",
		"name_key": "weapon.blade_long.name",
		"desc_key": "weapon.blade_long.desc",
		"base_cost": 6,
		"color": Color(0.85, 0.25, 0.25, 1.0),
		"swing_texture_path": "res://assets/weapons/swing_blade_short.png",
		"icon_path": "res://assets/weapons/blade_short.png",
		"stats": {
			"damage": 18,
			"cooldown": 0.48,
			"range": 88.0,
			"touch_interval": 0.42,
			"swing_duration": 0.24,
			"swing_degrees": 90.0,
			"swing_reach": 28.0,
			"hitbox_radius": 15.0
		}
	},
	{
		"id": "crossbow",
		"type": "ranged",
		"type_affix_id": "type_firearm",
		"theme_affix_id": "theme_classical",
		"script_path": "res://scripts/weapons/ranged/weapon_crossbow.gd",
		"name_key": "weapon.crossbow.name",
		"desc_key": "weapon.crossbow.desc",
		"base_cost": 8,
		"color": Color(0.55, 0.45, 0.35, 1.0),
		"bullet_type": "rifle",
		"icon_path": "res://assets/weapons/rifle_long.png",
		"bullet_texture_path": "res://assets/bullets/bullet_firearm.png",
		"bullet_collision_radius": 2.5,
		"stats": {"damage": 22, "cooldown": 0.65, "range": 1300.0, "bullet_speed": 680.0, "pellet_count": 1, "spread_degrees": 0.0, "bullet_pierce": 1}
	},
	{
		"id": "elemental_staff",
		"type": "ranged",
		"type_affix_id": "type_staff",
		"theme_affix_id": "theme_fantasy",
		"script_path": "res://scripts/weapons/ranged/weapon_elemental_staff.gd",
		"name_key": "weapon.elemental_staff.name",
		"desc_key": "weapon.elemental_staff.desc",
		"base_cost": 9,
		"color": Color(0.95, 0.50, 0.90, 1.0),
		"bullet_type": "laser",
		"icon_path": "res://assets/weapons/wand_focus.png",
		"bullet_texture_path": "res://assets/bullets/bullet_laser.png",
		"bullet_collision_radius": 2.5,
		"stats": {"damage": 12, "cooldown": 0.30, "range": 1100.0, "bullet_speed": 580.0, "pellet_count": 1, "spread_degrees": 0.0, "bullet_pierce": 0}
	}
]
